<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP36dehH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP36dehH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP36dehH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP36dehH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerP36dehH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'P36dehH',
    'container.build_id' => '948c3476',
    'container.build_time' => 1519293026,
));
